server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    location / { try_files \ /index.html; }
    location /assets { expires 1y; }
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;
}
